### ISSUE TITLE
onUpdate doesn't work

### ISSUE THREAD

**Issue by arzakmiftakhul** [cabbi/modbus_client_tcp#1]
Sorry if I don't know what is `onUpdate` means. I think `onUpdate` will be executed if the value is changed. But I have to to run `await modbusClient.send(batteryTemperature.getReadRequest());` to execute `onUpdate` and get current value.

```
// Create a modbus int16 register element
  var batteryTemperature = ModbusUint16Register(
      name: "BatteryTemperature",
      type: ModbusElementType.holdingRegister,
      address: 22,
      uom: "°C",
      multiplier: 0.1,
      // onUpdate is not executed even the modbus value is changed
      onUpdate: (self) => print(self));
```

**Comment by cabbi** [comment]
`onUpdate` gives you an alternative way of handling register changes, but it is not mandatory.

Once you send a request you might check the result of the `send `method which is of type `ModbusResponseCode`.

```dart
var res = await modbusClient.send(batteryTemperature.getReadRequest());
if (res == ModbusResponseCode.requestSucceed) {
   print(batteryTemperature.value);
}
```

Back to your issue: please let me know if you do not get `onUpdate`  called even if `send `method succeeded. 
In case please send me your code because I get  `onUpdate`  called if sending a requests succeeds and the register value has been changed.

**Comment by cabbi** [comment]
Got no response. Going to close as not reproducible.

**Comment by cabbi** [comment]
Got no response. Going to close as not reproducible
